import pandas as pd
a=pd.Series([10,20,30,40,50])
b=pd.Series([40,50,60,70,80])
print("series a:")
print(a)
print("/n series b:")
print(b)
non_com=a[~a.isin(b)].tolist()+b[~b.isin(b)].tolist()
print(" item not common to both series")
print(non_com)
print("\n sum of series B:\n",b.sum())
print("\n average of series A:\n",a.mean())
print("\n mediam of series B:\n",a.median())
print("\n largest element os series A:\n",a.max())
print("\n smallest element of series A:\n",a.min())